// Banque de mots — chaque paire = [motCivil, motUndercover]
// Les paires sont pensées pour être proches mais pas évidentes (même registre, même époque, même rôle)

const WORD_BANK = {

  "dessins-animes": {
    label: "Dessins animés",
    icon: "📺",
    pairs: [
      ["Bob l'éponge", "Patrick l'étoile de mer"],
      ["Ben 10", "Beyblade"],
      ["Les Razmoket", "Les Simpson"],
      ["Kim Possible", "Foster la maison des amis imaginaires"],
      ["Cory dans la boîte", "Phineas et Ferb"],
      ["Le Monde de Gumball", "Les Nouvelles Aventures de Sammy"],
      ["Adventure Time", "Regular Show"],
      ["Steven Universe", "Star vs les Forces du Mal"],
      ["Gravity Falls", "Randy le lycéen ninja"],
      ["Teen Titans Go", "Les Nouveaux Héros"],
      ["Avatar le dernier maître de l'air", "La Légende de Korra"],
      ["Code Lyoko", "W.I.T.C.H."],
      ["Martin Mystère", "Scooby-Doo"],
      ["Il était une fois... la vie", "C'est pas sorcier"],
      ["Oggy et les Cafards", "Tom et Jerry"],
      ["Titeuf", "Cédric"],
      ["Les Zinzins de l'espace", "Cyberchase"],
      ["Loulou et compagnie", "Trotro"],
      ["Peppa Pig", "Pat'Patrouille"],
      ["Miraculous Ladybug", "Les Sisters"],
      ["Yakari", "Rox et Rouky"],
      ["Grimault", "Les Aventures de Tintin"],
      ["Sonic Boom", "Sonic X"],
      ["Pokémon", "Digimon"],
      ["Dragon Ball Z", "Yu-Gi-Oh"],
      ["Naruto", "Bleach"],
      ["One Piece", "Fairy Tail"],
      ["Inazuma Eleven", "Olive et Tom"],
      ["Détective Conan", "Sherlock Holmes"],
      ["Bienvenue chez les Loud", "Bob's Burgers"],
      ["Wakfu", "Dofus"],
      ["Ninjago", "Beyblade Burst"],
      ["Slugterra", "Monster Hunter Stories"],
      ["Pyjamasques", "Super 4"],
      ["Vic le Viking", "Il était une fois... l'Homme"],
      ["Les Lapins Crétins", "Rabbids Invasion"],
      ["Molusco", "Bob l'éponge"]
    ]
  },

  "super-heros": {
    label: "Super-héros",
    icon: "🦸",
    pairs: [
      ["Iron Man", "War Machine"],
      ["Captain America", "Bucky Barnes"],
      ["Thor", "Loki"],
      ["Hulk", "Abomination"],
      ["Black Widow", "Hawkeye"],
      ["Spider-Man", "Miles Morales"],
      ["Doctor Strange", "Scarlet Witch"],
      ["Black Panther", "Killmonger"],
      ["Ant-Man", "Wasp"],
      ["Vision", "Ultron"],
      ["Star-Lord", "Gamora"],
      ["Rocket Raccoon", "Groot"],
      ["Batman", "Nightwing"],
      ["Superman", "Supergirl"],
      ["Wonder Woman", "Zatanna"],
      ["The Flash", "Kid Flash"],
      ["Green Lantern", "Green Arrow"],
      ["Aquaman", "Namor"],
      ["Cyborg", "Robocop"],
      ["Joker", "Harley Quinn"],
      ["Bane", "Killer Croc"],
      ["Wolverine", "Sabretooth"],
      ["Cyclops", "Havok"],
      ["Storm", "Rogue"],
      ["Professor X", "Magneto"],
      ["Deadpool", "Domino"],
      ["Jean Grey", "Emma Frost"],
      ["Nightcrawler", "Beast"],
      ["Daredevil", "Punisher"],
      ["Ghost Rider", "Blade"],
      ["Luke Cage", "Iron Fist"],
      ["Shazam", "Captain Marvel"],
      ["Martian Manhunter", "Green Lantern John Stewart"],
      ["Hawkgirl", "Black Canary"],
      ["Venom", "Carnage"],
      ["Thanos", "Darkseid"],
      ["Loki", "Mystique"],
      ["Quicksilver", "Speedy"]
    ]
  },

  "football": {
    label: "Football",
    icon: "⚽",
    pairs: [
      // Attaquants stars mondiaux
      ["Kylian Mbappé", "Erling Haaland"],
      ["Vinicius Jr", "Rodrygo"],
      ["Bukayo Saka", "Phil Foden"],
      ["Jude Bellingham", "Federico Valverde"],
      ["Ousmane Dembélé", "Khvicha Kvaratskhelia"],
      ["Lamine Yamal", "Nico Williams"],
      ["Victor Osimhen", "Randal Kolo Muani"],
      ["Marcus Rashford", "Cole Palmer"],
      ["Rafael Leão", "Christian Pulisic"],
      // Milieux
      ["Rodri", "Declan Rice"],
      ["Aurélien Tchouaméni", "Eduardo Camavinga"],
      ["Martin Ødegaard", "Bruno Fernandes"],
      ["Frenkie de Jong", "Pedri"],
      ["Warren Zaïre-Emery", "Manu Koné"],
      ["Adrien Rabiot", "Youssouf Fofana"],
      // Défenseurs
      ["William Saliba", "Milan Škriniar"],
      ["Virgil van Dijk", "Rúben Dias"],
      ["Dayot Upamecano", "Josko Gvardiol"],
      ["Achraf Hakimi", "Theo Hernández"],
      ["Jules Koundé", "Marquinhos"],
      // Gardiens
      ["Mike Maignan", "Alisson Becker"],
      ["Thibaut Courtois", "Marc-André ter Stegen"],
      ["Gianluigi Donnarumma", "Yann Sommer"],
      // Clubs Ligue 1
      ["Ousmane Dembélé", "Bradley Barcola"],
      ["Alexandre Lacazette", "Jonathan David"],
      ["Habib Diallo", "Emanuel Emegha"],
      ["Bilal Brahimi", "Amine Gouiri"],
      ["Elye Wahi", "Neal Maupay"],
      // Premier League
      ["Mohamed Salah", "Son Heung-min"],
      ["Kevin De Bruyne", "İlkay Gündoğan"],
      ["Alexander Isak", "Ollie Watkins"],
      ["Bernardo Silva", "Jack Grealish"],
      ["Dominic Solanke", "Nicolas Jackson"],
      // Liga
      ["Robert Lewandowski", "Álvaro Morata"],
      ["Antoine Griezmann", "João Félix"],
      ["Pedri", "Gavi"],
      ["Toni Kroos", "Luka Modrić"],
      // Serie A
      ["Lautaro Martínez", "Dušan Vlahović"],
      ["Paulo Dybala", "Nicolò Zaniolo"],
      ["Rafael Leão", "Federico Chiesa"],
      ["Marcus Thuram", "Romelu Lukaku"],
      // Bundesliga
      ["Jamal Musiala", "Florian Wirtz"],
      ["Harry Kane", "Serhou Guirassy"],
      ["Xavi Simons", "Jonas Hofmann"]
    ]
  },

  "animes": {
    label: "Animés (Blue Lock, Kuroko, SNK, HxH)",
    icon: "🎌",
    pairs: [
      // Blue Lock
      ["Yoichi Isagi", "Meguru Bachira"],
      ["Rensuke Kunigami", "Hyoma Chigiri"],
      ["Reo Mikage", "Shion Otoya"],
      ["Ranze Hiori", "Yudai Kurona"],
      ["Rin Itoshi", "Sae Itoshi"],
      ["Seishiro Nagi", "Aoshi Tokimitsu"],
      ["Jinpachi Ego", "Anri Teieri"],
      ["Yukimiya Kenyu", "Zantetsu Tsurugi"],
      ["Ikki Niko", "Wataru Kuon"],
      ["Gagamaru Gin", "Iori Kurona"],
      // Kuroko's Basketball
      ["Tetsuya Kuroko", "Taiga Kagami"],
      ["Ryota Kise", "Shintaro Midorima"],
      ["Daiki Aomine", "Atsushi Murasakibara"],
      ["Seijuro Akashi", "Satsuki Momoi"],
      ["Shun Izuki", "Junpei Hyuga"],
      ["Shogo Haizaki", "Yoshinori Kiyoshi"],
      ["Makoto Hanamiya", "Hanamichi Sakuragi"],
      ["Kazunari Takao", "Reo Mibuchi"],
      ["Eikichi Nebuya", "Kotaro Hayama"],
      ["Kiyoshi Teppei", "Junpei Hyuga"],
      // SNK
      ["Eren Yeager", "Reiner Braun"],
      ["Mikasa Ackerman", "Annie Leonhart"],
      ["Armin Arlert", "Bertholdt Hoover"],
      ["Levi Ackerman", "Kenny Ackerman"],
      ["Erwin Smith", "Dot Pixis"],
      ["Jean Kirstein", "Connie Springer"],
      ["Sasha Blouse", "Ymir"],
      ["Historia Reiss", "Frieda Reiss"],
      ["Hange Zoë", "Moblit Berner"],
      ["Zeke Yeager", "Grisha Yeager"],
      ["Falco Grice", "Gabi Braun"],
      ["Pieck Finger", "Porco Galliard"],
      // HxH
      ["Gon Freecss", "Killua Zoldyck"],
      ["Kurapika", "Leorio Paradinight"],
      ["Hisoka Morow", "Chrollo Lucilfer"],
      ["Illumi Zoldyck", "Milluki Zoldyck"],
      ["Kite", "Ging Freecss"],
      ["Meruem", "Netero"],
      ["Shalnark", "Phinks Magcub"],
      ["Feitan", "Machi Komacine"],
      ["Nobunaga Hazama", "Franklin Bordeau"],
      ["Neferpitou", "Shaiapouf"],
      ["Biscuit Krueger", "Wing"],
      ["Komugi", "Palm Siberia"]
    ]
  },

  "jeux-video": {
    label: "Jeux vidéo",
    icon: "🎮",
    pairs: [
      ["Mario Kart", "Sonic Racing"],
      ["GTA 5", "GTA IV San Andreas"],
      ["GTA 6", "Red Dead Redemption"],
      ["FIFA", "PES"],
      ["NBA 2K", "Inazuma Eleven Strikers"],
      ["Minecraft", "Terraria"],
      ["Fortnite", "Call of Duty Warzone"],
      ["Call of Duty", "Battlefield"],
      ["Tetris", "Candy Crush"],
      ["Habbo", "Club Penguin"],
      ["The Last of Us", "Resident Evil"],
      ["Splatoon", "Overwatch"],
      ["Rocket League", "Mario Kart"],
      ["Among Us", "Fall Guys"],
      ["Roblox", "Habbo"],
      ["Brawl Stars", "Clash Royale"],
      ["Clash of Clans", "Boom Beach"],
      ["Subway Surfers", "Temple Run"],
      ["Just Dance", "Sing Star"],
      ["Wii Sports", "Wii Fit"],
      ["Mario Party", "Overcooked"],
      ["Animal Crossing", "Stardew Valley"],
      ["Zelda Breath of the Wild", "Genshin Impact"],
      ["Super Smash Bros", "Brawlhalla"],
      ["FIFA Street", "NBA Street"],
      ["Warzone", "Apex Legends"],
      ["League of Legends", "Dota 2"],
      ["Valorant", "Counter-Strike"],
      ["PUBG Mobile", "Free Fire"],
      ["Rainbow Six Siege", "Call of Duty"],
      ["Assassin's Creed", "Watch Dogs"],
      ["Red Dead Redemption", "GTA 5"],
      ["FarCry", "Metal Gear Solid"],
      ["God of War", "Kratos"],
      ["Uncharted", "Tomb Raider"],
      ["Sonic Racing", "Crash Team Racing"]
    ]
  },

  "films-series": {
    label: "Films / Séries",
    icon: "🎬",
    pairs: [
      // Persos comme titres, univers proches
      ["Harry Potter", "Percy Jackson"],
      ["Le Seigneur des Anneaux", "Le Hobbit"],
      ["Star Wars", "Star Trek"],
      ["Avengers", "Justice League"],
      ["Fast and Furious", "Transformers"],
      ["Mission Impossible", "James Bond"],
      ["John Wick", "Taken"],
      ["Breaking Bad", "Better Call Saul"],
      ["Stranger Things", "Dark"],
      ["Peaky Blinders", "La Casa de Papel"],
      ["Game of Thrones", "House of the Dragon"],
      ["The Walking Dead", "World War Z"],
      ["Vikings", "The Last Kingdom"],
      ["Sherlock", "Detective Conan"],
      ["Prison Break", "Money Heist"],
      ["Friends", "How I Met Your Mother"],
      ["The Office", "Brooklyn Nine-Nine"],
      ["Squid Game", "Alice in Borderland"],
      ["Wednesday", "Sabrina"],
      ["Emily in Paris", "Sex and the City"],
      // Disney/Pixar
      ["Le Roi Lion", "Frère des Ours"],
      ["Toy Story", "Cars"],
      ["Ratatouille", "Wall-E"],
      ["Là-haut", "Coco"],
      ["Vice-Versa", "Soul"],
      ["La Reine des Neiges", "Raiponce"],
      ["Aladdin", "Le Livre de la Jungle"],
      ["Moana Vaiana", "Encanto"],
      ["Zootopie", "Luca"],
      ["Monstres et Cie", "Les Indestructibles"],
      ["Rebelle", "Mulan"],
      ["La Belle et la Bête", "La Petite Sirène"],
      ["Cendrillon", "Blanche-Neige"],
      ["Peter Pan", "Alice au Pays des Merveilles"],
      ["Shrek", "L'Âge de Glace"],
      ["Madagascar", "Kung Fu Panda"],
      ["Dragons", "Là-haut"],
      ["Sacrées Sorcières", "Charlie et la Chocolaterie"],
      // Films
      ["Inception", "Interstellar"],
      ["Matrix", "Blade Runner"],
      ["Jurassic Park", "King Kong"],
      ["Titanic", "La La Land"],
      ["Joker", "Le Loup de Wall Street"],
      ["Parasite", "Get Out"],
      ["Le Parrain", "Scarface"],
      ["Rocky", "Creed"],
      ["Gladiator", "300"],
      ["Pirates des Caraïbes", "Indiana Jones"]
    ]
  }
};
