// Banque de mots — chaque paire = [motCivil, motUndercover]
// Les paires sont pensées pour être proches mais pas évidentes (même registre, même époque, même rôle)

const WORD_BANK = {

  "dessins-animes": {
    label: "Dessins animés",
    icon: "📺",
    pairs: [
      ["Bob l'éponge", "Patrick l'étoile de mer"],
      ["Ben 10", "Beyblade"],
      ["Code Lyoko", "Martin Mystère"],
      ["Scooby-Doo", "Inspecteur Gadget"],
      ["Oggy et les Cafards", "Les Ratz"],
      ["Titeuf", "Cédric"],
      ["Loulou et compagnie", "Trotro"],
      ["Peppa Pig", "Pat'Patrouille"],
      ["Miraculous Ladybug", "Les Sisters"],
      ["Yakari", "Rox et Rouky"],
      ["Sonic Boom", "Sonic X"],
      ["Pokémon", "Digimon"],
      ["Inazuma Eleven", "Inazuma Eleven Go"],
      ["Bienvenue chez les Loud", "Bob's Burgers"],
      ["Wakfu", "Dofus"],
      ["Ninjago", "Beyblade Burst"],
      ["Slugterra", "Monster Hunter Stories"],
      ["Pyjamasques", "Super 4"],
      ["Vic le Viking", "Il était une fois... l'Homme"],
      ["Les Lapins Crétins", "Rabbids Invasion"],
      ["Molusco", "Bob l'éponge"],
      ["SpieZ", "Totally Spies"],
      ["Les Aventures du Petit Ours Brun", "Tchoupi et Doudou"],
      ["Franklin", "Clifford"],
      ["Oui-Oui", "SamSam"],
      ["Les Pingouins de Madagascar", "Madagascar"],
      ["La Panthère Rose", "Woody Woodpecker"],
      ["Dora l'Exploratrice", "Diego"],
      ["Looney Tunes", "Tom et Jerry"],
      ["Mickey Mouse", "Donald Duck"],
      ["Woody Woodpecker", "Sid le Petit Scientifique"],
      ["Les Minijusticiers", "Les P'tits Diables"],
      ["Foot 2 Rue", "Foot 2 Rue Extrême"],
      ["Inazuma Eleven Go", "Galactik Football"],
      ["Spirou", "Lucky Luke"],
      ["Kim Possible", "Atomic Betty"],
      ["Babar", "Franklin"],
      ["Famille Pirate", "La Famille Delajungle"],
      ["Galactik Football", "Redakai"],
      ["Redakai", "Beyblade"],
      ["Télétubbies", "Barbapapa"],
      ["Tom-Tom et Nana", "Petit Nicolas"],
      ["Martine", "SamSam"],
      ["Petit Nicolas", "Le Club des Cinq"],
      ["Angelo la Débrouille", "Titeuf"],
      ["Les Daltons", "Lucky Luke"],
      ["Sid le Petit Scientifique", "C'est pas sorcier"],
      ["Les Histoires du Père Castor", "Barbapapa"],
      ["Les Schtroumpfs", "Garfield & Cie"],
      ["Garfield & Cie", "Titi et Grosminet"],
      ["Les Ratz", "Oggy et les Cafards"],
      ["Tortues Ninja", "Shuriken School"],
      ["Shuriken School", "Ninjago"],
      ["Martin Matin", "Marcelino"],
      ["Le Livre de la Jungle", "Aladdin"],
      ["Les Zinzins de l'Espace", "Dino Train"],
      ["Lucky Luke", "Les Daltons"],
      ["Aladdin", "Corneil et Bernie"],
      ["Corneil et Bernie", "Jimmy Neutron"],
      ["Jimmy Neutron", "Manny et ses Outils"],
      ["Les Mystérieuses Cités d'Or", "Il était une fois... l'Espace"],
      ["Sally Bollywood", "Martin Mystère"],
      ["Magic", "Winx Club"],
      ["Manny et ses Outils", "Bob le Bricoleur"],
      ["Winx Club", "My Little Pony"],
      ["Atomic Betty", "SpieZ"],
      ["Dino Train", "Le Livre de la Jungle"],
      ["Sam le Pompier", "Manny et ses Outils"],
      ["Les Sisters", "Charlotte aux Fraises"],
      ["Lou", "Martine"],
      ["Robocar Poli", "Sam le Pompier"],
      ["Didou", "Franklin"],
      ["Jack et les Pirates", "Famille Pirate"],
      ["Robin des Bois", "Le Livre de la Jungle"],
      ["Zig et Sharko", "Oggy et les Cafards"],
      ["Mr Bean", "La Panthère Rose"],
      ["Ariel", "Le Club des Cinq"],
      ["Titi et Grosminet", "Tom et Jerry"],
      ["Barbapapa", "Télétubbies"],
      ["My Little Pony", "Charlotte aux Fraises"],
      ["Charlotte aux Fraises", "My Little Pony"],
      ["Le Club des Cinq", "Les Mystérieuses Cités d'Or"],
      ["Phineas et Ferb", "SamSam"],
      ["SamSam", "Oui-Oui"],
      ["Tchoupi et Doudou", "Les Aventures du Petit Ours Brun"],
      ["Clifford", "Franklin"],
      ["Diego", "Dora l'Exploratrice"],
      ["Madagascar", "Les Pingouins de Madagascar"],
      ["Woody Woodpecker", "Looney Tunes"],
      ["Donald Duck", "Mickey Mouse"],
      ["Les P'tits Diables", "Les Minijusticiers"],
      ["Foot 2 Rue Extrême", "Foot 2 Rue"],
      ["Galactik Football", "Foot 2 Rue"],
      ["Lucky Luke", "Spirou"],
      ["Atomic Betty", "Kim Possible"],
      ["Franklin", "Babar"],
      ["La Famille Delajungle", "Famille Pirate"],
      ["Redakai", "Galactik Football"],
      ["Beyblade", "Redakai"],
      ["Barbapapa", "Télétubbies"],
      ["Petit Nicolas", "Tom-Tom et Nana"],
      ["SamSam", "Martine"],
      ["Le Club des Cinq", "Petit Nicolas"],
      ["Titeuf", "Angelo la Débrouille"],
      ["Lucky Luke", "Les Daltons"],
      ["C'est pas sorcier", "Sid le Petit Scientifique"],
      ["Barbapapa", "Les Histoires du Père Castor"],
      ["Garfield & Cie", "Les Schtroumpfs"],
      ["Titi et Grosminet", "Garfield & Cie"],
      ["Oggy et les Cafards", "Les Ratz"],
      ["Shuriken School", "Tortues Ninja"],
      ["Ninjago", "Shuriken School"],
      ["Marcelino", "Martin Matin"],
      ["Aladdin", "Le Livre de la Jungle"],
      ["Dino Train", "Les Zinzins de l'Espace"],
      ["Les Daltons", "Lucky Luke"],
      ["Corneil et Bernie", "Aladdin"],
      ["Jimmy Neutron", "Corneil et Bernie"],
      ["Manny et ses Outils", "Jimmy Neutron"],
      ["Il était une fois... l'Espace", "Les Mystérieuses Cités d'Or"],
      ["Martin Mystère", "Sally Bollywood"],
      ["Winx Club", "Magic"],
      ["Bob le Bricoleur", "Manny et ses Outils"],
      ["My Little Pony", "Winx Club"],
      ["SpieZ", "Atomic Betty"],
      ["Le Livre de la Jungle", "Dino Train"],
      ["Manny et ses Outils", "Sam le Pompier"],
      ["Charlotte aux Fraises", "Les Sisters"],
      ["Martine", "Lou"],
      ["Sam le Pompier", "Robocar Poli"],
      ["Franklin", "Didou"],
      ["Famille Pirate", "Jack et les Pirates"],
      ["Le Livre de la Jungle", "Robin des Bois"],
      ["Oggy et les Cafards", "Zig et Sharko"],
      ["La Panthère Rose", "Mr Bean"],
      ["Le Club des Cinq", "Ariel"],
      ["Tom et Jerry", "Titi et Grosminet"],
      ["Télétubbies", "Barbapapa"],
      ["Charlotte aux Fraises", "My Little Pony"],
      ["Les Mystérieuses Cités d'Or", "Le Club des Cinq"],
      ["SamSam", "Phineas et Ferb"],
      ["Yakari", "Vic le Viking"],
      ["Ben 10", "Slugterra"],
      ["Bob l'éponge", "Zig et Sharko"],
      ["Pokémon", "Beyblade"],
      ["Digimon", "Slugterra"],
      ["Inazuma Eleven", "Foot 2 Rue"],
      ["Inazuma Eleven Go", "Foot 2 Rue Extrême"],
      ["Code Lyoko", "SpieZ"],
      ["Miraculous Ladybug", "Totally Spies"],
      ["Wakfu", "Ninjago"],
      ["Dofus", "Slugterra"],
      ["Pyjamasques", "Les Minijusticiers"],
      ["Super 4", "Pyjamasques"],
      ["Vic le Viking", "Marcelino"],
      ["Les Lapins Crétins", "Looney Tunes"],
      ["Rabbids Invasion", "Woody Woodpecker"],
      ["Molusco", "Bienvenue chez les Loud"],
      ["Bob's Burgers", "Bienvenue chez les Loud"],
      ["Scooby-Doo", "Sally Bollywood"],
      ["Inspecteur Gadget", "Martin Mystère"],
      ["Cédric", "Angelo la Débrouille"],
      ["Trotro", "Loulou et compagnie"],
      ["Pat'Patrouille", "Robocar Poli"],
      ["Les Sisters", "Winx Club"],
      ["Rox et Rouky", "Le Livre de la Jungle"],
      ["Sonic X", "Sonic Boom"],
      ["Digimon", "Pokémon"],
      ["Tortues Ninja", "Ninjago"],
      ["Marcelino", "Il était une fois... l'Homme"],
      ["Dino Train", "Il était une fois... l'Espace"],
      ["Corneil et Bernie", "Le Livre de la Jungle"],
      ["Manny et ses Outils", "Robocar Poli"],
      ["Sally Bollywood", "Inspecteur Gadget"],
      ["Magic", "My Little Pony"],
      ["Bob le Bricoleur", "Sam le Pompier"],
      ["Atomic Betty", "Totally Spies"],
      ["Dino Train", "Yakari"],
      ["Sam le Pompier", "Pat'Patrouille"],
      ["Les Sisters", "Titeuf"],
      ["Lou", "Tom-Tom et Nana"],
      ["Robocar Poli", "Bob le Bricoleur"],
      ["Didou", "Tchoupi et Doudou"],
      ["Jack et les Pirates", "Famille Pirate"],
      ["Robin des Bois", "Aladdin"],
      ["Zig et Sharko", "Bob l'éponge"],
      ["Mr Bean", "Cédric"],
      ["Ariel", "Charlotte aux Fraises"],
      ["Titi et Grosminet", "Looney Tunes"],
      ["Barbapapa", "Les Histoires du Père Castor"],
      ["My Little Pony", "Ariel"],
      ["Charlotte aux Fraises", "Lou"],
      ["Le Club des Cinq", "Les Mystérieuses Cités d'Or"],
      ["Phineas et Ferb", "Jimmy Neutron"],
      ["Iron Man", "Batman"],
      ["Superman", "Batman"],
      ["Iron Man", "Superman"]
    ]
  },

  "super-heros": {
    label: "Super-héros",
    icon: "🦸",
    pairs: [
      ["Iron Man", "War Machine"],
      ["Captain America", "Bucky Barnes"],
      ["Thor", "Loki"],
      ["Hulk", "She-Hulk"],
      ["Black Widow", "Hawkeye"],
      ["Spider-Man", "Miles Morales"],
      ["Doctor Strange", "Scarlet Witch"],
      ["Black Panther", "Killmonger"],
      ["Ant-Man", "Falcon"],
      ["Vision", "Ultron"],
      ["Star-Lord", "Gamora"],
      ["Rocket Raccoon", "Groot"],
      ["Batman", "Nightwing"],
      ["Superman", "Supergirl"],
      ["Wonder Woman", "Harley Quinn"],
      ["The Flash", "Green Lantern"],
      ["Green Lantern", "Green Arrow"],
      ["Aquaman", "Cyborg"],
      ["Cyborg", "Batman"],
      ["Joker", "Harley Quinn"],
      ["Wolverine", "Deadpool"],
      ["Deadpool", "Spider-Man"],
      ["Daredevil", "Punisher"],
      ["Luke Cage", "Iron Fist"],
      ["Shazam", "Captain Marvel"],
      ["Venom", "Spider-Man"],
      ["Thanos", "Darkseid"],
      ["Loki", "Joker"],
      ["Magneto", "Professeur X"],
      ["Magneto", "Thanos"],
      ["Hulk", "Thor"],
      ["Captain Marvel", "Wonder Woman"],
      ["Black Widow", "Catwoman"],
      ["Catwoman", "Harley Quinn"],
      ["Batman", "Iron Man"],
      ["Superman", "Captain America"],
      ["Spider-Man", "Batman"],
      ["Hulk", "Superman"],
      ["Wolverine", "Batman"],
      ["Green Arrow", "Hawkeye"],
      ["Aquaman", "Namor"],
      ["Iron Man", "Doctor Strange"],
      ["Thor", "Aquaman"],
      ["Black Panther", "Batman"],
      ["Wonder Woman", "Black Widow"],
      ["Deadpool", "Joker"],
      ["Venom", "Hulk"],
      ["Captain America", "Superman"],
      ["The Flash", "Quicksilver"],
      ["Nightwing", "Robin"],
      ["Robin", "Batgirl"]
    ]
  },

  "football": {
    label: "Football",
    icon: "⚽",
    pairs: [
      // Stars mondiales / Ballon d'Or
      ["Kylian Mbappé", "Erling Haaland"],
      ["Vinicius Jr", "Rodrygo"],
      ["Bukayo Saka", "Phil Foden"],
      ["Jude Bellingham", "Federico Valverde"],
      ["Ousmane Dembélé", "Khvicha Kvaratskhelia"],
      ["Lamine Yamal", "Nico Williams"],
      ["Victor Osimhen", "Randal Kolo Muani"],
      ["Marcus Rashford", "Cole Palmer"],
      ["Rafael Leão", "Christian Pulisic"],
      ["Rodri", "Declan Rice"],
      ["Aurélien Tchouaméni", "Eduardo Camavinga"],
      ["Martin Ødegaard", "Bruno Fernandes"],
      ["Frenkie de Jong", "Pedri"],
      ["Warren Zaïre-Emery", "Manu Koné"],
      ["Adrien Rabiot", "Youssouf Fofana"],
      ["William Saliba", "Milan Škriniar"],
      ["Virgil van Dijk", "Rúben Dias"],
      ["Dayot Upamecano", "Josko Gvardiol"],
      ["Achraf Hakimi", "Theo Hernández"],
      ["Jules Koundé", "Marquinhos"],
      ["Mike Maignan", "Alisson Becker"],
      ["Thibaut Courtois", "Andriy Lunin"],
      ["Gianluigi Donnarumma", "Yann Sommer"],
      ["Robert Lewandowski", "Álvaro Morata"],
      ["Antoine Griezmann", "João Félix"],
      ["Pedri", "Gavi"],
      ["Arda Güler", "Brahim Díaz"],
      ["Lautaro Martínez", "Dušan Vlahović"],
      ["Rafael Leão", "Federico Chiesa"],
      ["Marcus Thuram", "Romelu Lukaku"],
      ["Jamal Musiala", "Florian Wirtz"],
      ["Harry Kane", "Serhou Guirassy"],

      // PSG (effectif 2025/2026)
      ["Ousmane Dembélé", "Bradley Barcola"],
      ["Vitinha", "Fabián Ruiz"],
      ["Marquinhos", "Achraf Hakimi"],
      ["Désiré Doué", "Senny Mayulu"],
      ["Nuno Mendes", "Lucas Hernandez"],
      ["Warren Zaïre-Emery", "João Neves"],
      ["Randal Kolo Muani", "Gonçalo Ramos"],
      ["Lucas Chevalier", "Matvey Safonov"],
      ["Willian Pacho", "Ilya Zabarnyi"],
      ["Kang-In Lee", "Khvicha Kvaratskhelia"],
      ["Lucas Beraldo", "Yoram Zague"],
      ["Renato Sanches", "Ibrahim Mbaye"],

      // Marseille (OM)
      ["Mason Greenwood", "Amine Harit"],
      ["Pierre-Emerick Aubameyang", "Elye Wahi"],
      ["Adrien Rabiot", "Geoffrey Kondogbia"],
      ["Jean-Clair Todibo", "Leonardo Balerdi"],

      // Lyon (OL)
      ["Alexandre Lacazette", "Rayan Cherki"],
      ["Corentin Tolisso", "Malick Fofana"],

      // Lille (LOSC)
      ["Jonathan David", "Edon Zhegrova"],

      // Lens (RCL)
      ["Kevin Danso", "Facundo Medina"],
      ["Brice Samba", "Robin Risser"],

      // Rennes (SRFC)

      // Strasbourg (RCSA)
      ["Habib Diallo", "Emanuel Emegha"],

      // Autres Ligue 1
      ["Folarin Balogun", "Wissam Ben Yedder"],

      // Premier League — Man City / Man United
      ["Kevin De Bruyne", "İlkay Gündoğan"],
      ["Erling Haaland", "Julián Álvarez"],
      ["Phil Foden", "Jack Grealish"],
      ["Bruno Fernandes", "Marcus Rashford"],
      ["Alejandro Garnacho", "Mason Mount"],
      ["Rúben Dias", "Nathan Aké"],
      ["Kobbie Mainoo", "Casemiro"],

      // Arsenal / Chelsea
      ["Bukayo Saka", "Gabriel Martinelli"],
      ["Martin Ødegaard", "Declan Rice"],
      ["Gabriel Jesus", "Kai Havertz"],
      ["William Saliba", "Gabriel Magalhães"],
      ["Cole Palmer", "Nicolas Jackson"],
      ["Enzo Fernández", "Moisés Caicedo"],
      ["Raheem Sterling", "Christopher Nkunku"],
      ["Reece James", "Levi Colwill"],

      // Liverpool / Tottenham
      ["Mohamed Salah", "Son Heung-min"],
      ["Darwin Núñez", "Luis Díaz"],
      ["Virgil van Dijk", "Ibrahima Konaté"],
      ["Dominik Szoboszlai", "Alexis Mac Allister"],
      ["James Maddison", "Dejan Kulusevski"],
      ["Cristian Romero", "Micky van de Ven"],
      ["Richarlison", "Yves Bissouma"],

      // Newcastle / Aston Villa / autres PL
      ["Alexander Isak", "Ollie Watkins"],
      ["Anthony Gordon", "Jacob Ramsey"],
      ["Bruno Guimarães", "Youri Tielemans"],
      ["Bryan Mbeumo", "Yoane Wissa"],

      // Barça (effectif 2025/2026)
      ["Robert Lewandowski", "Ferran Torres"],
      ["Raphinha", "Marcus Rashford"],
      ["Frenkie de Jong", "Pedri"],
      ["Ronald Araújo", "Pau Cubarsí"],
      ["Joan García", "Wojciech Szczęsny"],
      ["Alejandro Balde", "Gerard Martín"],
      ["Dani Olmo", "Fermín López"],
      ["Eric García", "João Cancelo"],
      ["Jules Koundé", "Gavi"],
      ["Lamine Yamal", "Fermín López"],

      // Real Madrid (effectif 2025/2026)
      ["Vinicius Jr", "Rodrygo"],
      ["Jude Bellingham", "Federico Valverde"],
      ["Aurélien Tchouaméni", "Eduardo Camavinga"],
      ["Éder Militão", "Antonio Rüdiger"],
      ["Dani Carvajal", "Ferland Mendy"],
      ["Thibaut Courtois", "Andriy Lunin"],
      ["Dean Huijsen", "Raúl Asencio"],
      ["Arda Güler", "Brahim Díaz"],
      ["Kylian Mbappé", "Gonzalo García"],
      ["Fede Valverde", "Éder Militão"],

      // Atlético Madrid
      ["Antoine Griezmann", "Álvaro Morata"],
      ["Julián Álvarez", "Ángel Correa"],
      ["Koke", "Rodrigo De Paul"],
      ["José María Giménez", "Mario Hermoso"],

      // Naples (SSC Napoli)
      ["Victor Osimhen", "Romelu Lukaku"],
      ["Stanislav Lobotka", "Piotr Zieliński"],

      // Inter Milan
      ["Lautaro Martínez", "Marcus Thuram"],
      ["Nicolò Barella", "Hakan Çalhanoğlu"],
      ["Federico Dimarco", "Denzel Dumfries"],
      ["Alessandro Bastoni", "Francesco Acerbi"],

      // AC Milan
      ["Rafael Leão", "Christian Pulisic"],
      ["Theo Hernández", "Fikayo Tomori"],
      ["Tijjani Reijnders", "Ismaël Bennacer"],

      // Juventus / Roma
      ["Dušan Vlahović", "Federico Chiesa"],
      ["Federico Gatti", "Gleison Bremer"],
      ["Paulo Dybala", "Lorenzo Pellegrini"],

      // Dortmund / Bayern / Leipzig (effectifs 2025/2026)
      ["Jamal Musiala", "Florian Wirtz"],
      ["Harry Kane", "Serhou Guirassy"],
      ["Karim Adeyemi", "Julian Brandt"],
      ["Niclas Füllkrug", "Youssoufa Moukoko"],
      ["Luis Díaz", "Nicolas Jackson"],
      ["Joshua Kimmich", "Konrad Laimer"],
      ["Manuel Neuer", "Jonas Urbig"],
      ["Dayot Upamecano", "Min-jae Kim"],
      ["Michael Olise", "Serge Gnabry"],
      ["Jonathan Tah", "Alphonso Davies"],
      ["Benjamin Šeško", "Loïs Openda"],
      ["Willi Orbán", "Castello Lukeba"],

      // Équipe de France (Coupe du Monde 2026)
      ["Mike Maignan", "Brice Samba"],
      ["Robin Risser", "Lucas Chevalier"],
      ["Lucas Digne", "Théo Hernandez"],
      ["Malo Gusto", "Jules Koundé"],
      ["Ibrahima Konaté", "Dayot Upamecano"],
      ["William Saliba", "Maxence Lacroix"],
      ["N'Golo Kanté", "Manu Koné"],
      ["Aurélien Tchouaméni", "Adrien Rabiot"],
      ["Warren Zaïre-Emery", "Rayan Cherki"],
      ["Kylian Mbappé", "Michael Olise"],
      ["Ousmane Dembélé", "Bradley Barcola"],
      ["Désiré Doué", "Maghnes Akliouche"],
      ["Marcus Thuram", "Jean-Philippe Mateta"],
      ["Lucas Hernandez", "Malo Gusto"]
    ]
  },

  "animes": {
    label: "Animés (Blue Lock, Kuroko, SNK, HxH)",
    icon: "🎌",
    pairs: [
      // Blue Lock
      ["Yoichi Isagi", "Meguru Bachira"],
      ["Rensuke Kunigami", "Hyoma Chigiri"],
      ["Rin Itoshi", "Sae Itoshi"],
      ["Seishiro Nagi", "Jinpachi Ego"],
      ["Anri Teieri", "Gagamaru Gin"],
      // Kuroko's Basketball
      ["Tetsuya Kuroko", "Taiga Kagami"],
      ["Ryota Kise", "Shintaro Midorima"],
      ["Daiki Aomine", "Atsushi Murasakibara"],
      ["Seijuro Akashi", "Satsuki Momoi"],
      ["Shun Izuki", "Kazunari Takao"],
      ["Shogo Haizaki", "Makoto Hanamiya"],
      ["Junpei Hyuga", "Kiyoshi Teppei"],
      ["Rinnosuke Mitobe", "Shinji Koganei"],
      ["Kagetora Aida", "Riko Aida"],
      ["Alexandra Garcia", "Riko Aida"],
      ["Tatsuya Himuro", "Taiga Kagami"],
      ["Jason Silver", "Nash Gold Jr"],
      ["Tetsuya 2", "Tetsuya Kuroko"],
      // SNK
      ["Eren Yeager", "Reiner Braun"],
      ["Mikasa Ackerman", "Annie Leonhart"],
      ["Armin Arlert", "Bertholdt Hoover"],
      ["Levi Ackerman", "Kenny Ackerman"],
      ["Erwin Smith", "Dot Pixis"],
      ["Jean Kirstein", "Connie Springer"],
      ["Sasha Blouse", "Ymir"],
      ["Historia Reiss", "Frieda Reiss"],
      ["Zeke Yeager", "Grisha Yeager"],
      ["Falco Grice", "Gabi Braun"],
      ["Hange Zoë", "Porco Galliard"],
      // HxH (noms français)
      ["Gon Freecss", "Kirua Zoldik"],
      ["Kurapika", "Leolio Paradinaito"],
      ["Hisoka Morow", "Kuroro Lucifer"],
      ["Miruki Zoldik", "Zeno Zoldik"],
      ["Silva Zoldik", "Karuto Zoldik"],
      ["Aruka Zoldik", "Kaito"],
      ["Ging Freecss", "Genthru Boomer"],
      ["Neferupito", "Pufu"],
      ["Pâmu Shiberia", "Biscuit Krueger"],
      ["Menchi", "Bendotto"],
      ["Jonest", "Leluto"],
      ["Majitani", "Sedokan"],
      ["Mito Freecss", "Abe Freecss"],
      ["Amane", "Kanaria"],
      ["Gotôt", "Ciquento"],
      ["Tsubone", "Zushi"],
      ["Kastrot", "Shizuku Murasaki"],
      ["Bonorenof Ndongo", "Uvogin"],
      ["Sharnalkt", "Tsezugerra"],
      ["Razor", "Satotsu"],
      ["Pariston Hill", "Tompa"],
      ["Beans", "Knuckle Bine"],
      ["Novu", "Hanzô"],
      ["La Reine des fourmis chimères", "Yupi"],
      ["Koruto", "Morel Mackernasey"],
      ["Werefin", "Flutter"],
      ["Burovûta", "Cheetu"]
    ]
  },

  "jeux-video": {
    label: "Jeux vidéo",
    icon: "🎮",
    pairs: [
      ["Mario Kart", "Sonic Racing"],
      ["GTA 5", "GTA IV San Andreas"],
      ["GTA 6", "Red Dead Redemption"],
      ["FIFA", "PES"],
      ["NBA 2K", "Inazuma Eleven Strikers"],
      ["Minecraft", "Terraria"],
      ["Fortnite", "Call of Duty Warzone"],
      ["Call of Duty", "Battlefield"],
      ["Tetris", "Candy Crush"],
      ["Habbo", "Club Penguin"],
      ["The Last of Us", "Resident Evil"],
      ["Splatoon", "Overwatch"],
      ["Rocket League", "Mario Kart"],
      ["Among Us", "Fall Guys"],
      ["Roblox", "Habbo"],
      ["Brawl Stars", "Clash Royale"],
      ["Clash of Clans", "Boom Beach"],
      ["Subway Surfers", "Temple Run"],
      ["Just Dance", "Sing Star"],
      ["Wii Sports", "Wii Fit"],
      ["Mario Party", "Overcooked"],
      ["Animal Crossing", "Stardew Valley"],
      ["Zelda Breath of the Wild", "Genshin Impact"],
      ["Super Smash Bros", "Brawlhalla"],
      ["FIFA Street", "NBA Street"],
      ["Warzone", "Apex Legends"],
      ["League of Legends", "Dota 2"],
      ["Valorant", "Counter-Strike"],
      ["PUBG Mobile", "Free Fire"],
      ["Rainbow Six Siege", "Call of Duty"],
      ["Assassin's Creed", "Watch Dogs"],
      ["Red Dead Redemption", "GTA 5"],
      ["FarCry", "Metal Gear Solid"],
      ["God of War", "Kratos"],
      ["Uncharted", "Tomb Raider"],
      ["Sonic Racing", "Crash Team Racing"]
    ]
  },

  "films-series": {
    label: "Films / Séries",
    icon: "🎬",
    pairs: [
      // Persos comme titres, univers proches
      ["Harry Potter", "Percy Jackson"],
      ["Le Seigneur des Anneaux", "Le Hobbit"],
      ["Star Wars", "Star Trek"],
      ["Avengers", "Justice League"],
      ["Fast and Furious", "Transformers"],
      ["Mission Impossible", "James Bond"],
      ["John Wick", "Taken"],
      ["Breaking Bad", "Better Call Saul"],
      ["Stranger Things", "Dark"],
      ["Peaky Blinders", "La Casa de Papel"],
      ["Game of Thrones", "House of the Dragon"],
      ["The Walking Dead", "World War Z"],
      ["Vikings", "The Last Kingdom"],
      ["Sherlock", "Detective Conan"],
      ["Prison Break", "Money Heist"],
      ["Friends", "How I Met Your Mother"],
      ["The Office", "Brooklyn Nine-Nine"],
      ["Squid Game", "Alice in Borderland"],
      ["Wednesday", "Sabrina"],
      ["Emily in Paris", "Sex and the City"],
      // Disney/Pixar
      ["Le Roi Lion", "Frère des Ours"],
      ["Toy Story", "Cars"],
      ["Ratatouille", "Wall-E"],
      ["Là-haut", "Coco"],
      ["Vice-Versa", "Soul"],
      ["La Reine des Neiges", "Raiponce"],
      ["Aladdin", "Le Livre de la Jungle"],
      ["Moana Vaiana", "Encanto"],
      ["Zootopie", "Luca"],
      ["Monstres et Cie", "Les Indestructibles"],
      ["Rebelle", "Mulan"],
      ["La Belle et la Bête", "La Petite Sirène"],
      ["Cendrillon", "Blanche-Neige"],
      ["Peter Pan", "Alice au Pays des Merveilles"],
      ["Shrek", "L'Âge de Glace"],
      ["Madagascar", "Kung Fu Panda"],
      ["Dragons", "Là-haut"],
      ["Sacrées Sorcières", "Charlie et la Chocolaterie"],
      // Films
      ["Inception", "Interstellar"],
      ["Matrix", "Blade Runner"],
      ["Jurassic Park", "King Kong"],
      ["Titanic", "La La Land"],
      ["Joker", "Le Loup de Wall Street"],
      ["Parasite", "Get Out"],
      ["Le Parrain", "Scarface"],
      ["Rocky", "Creed"],
      ["Gladiator", "300"],
      ["Pirates des Caraïbes", "Indiana Jones"]
    ]
  }
};
